name: Deploy Cloud Functions
run-name: ${{ github.actor }} is deploying cloud Functions
on:
  push:
    branches:
      - main
jobs:
  changes: 
    runs-on: ubuntu-latest
    outputs:
      http-python: ${{ steps.filter.outputs.http-python }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changes1
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            http-python:
            - 'http-python/**'
      
  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.http-python == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEPLOY_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>=363.0.0'
      #- name: 'Use gcloud CLI'
        # run: 'gcloud info'
      #- name: 'Install gcloud beta'
        # run: 'gcloud components install beta'
      - name: 'Deploy cloud function'
        run: |
          gcloud functions deploy python_http_function \
          --gen2 \
          --region=europe-north1 \
          --runtime=python310 \
          --source=./src/http-python/ \
          --trigger-http \
          --allow-unauthenticated
      - name: 'Attempt double deployment if function already manually created'
        run: |
          gcloud functions deploy double-deployment-test \
          --gen2 \
          --region=europe-north1 \
          --runtime=python310 \
          --source=./src/http-python \
          --entry-point python_http_function \
          --trigger-http \
          --allow-unauthenticated
