name: Deploy Cloud Functions
run-name: ${{ github.actor }} is deploying cloud Functions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_DEPLOY_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>=363.0.0'
      #- name: 'Use gcloud CLI'
        # run: 'gcloud info'
      #- name: 'Install gcloud beta'
        # run: 'gcloud components install beta'
      - name: 'Deploy cloud function'
        run: |
          gcloud functions deploy python_http_function \
          --gen2 \
          --region=europe-north1 \
          --runtime=python310 \
          --source=./src/http-python/ \
          --trigger-http \
          --allow-unauthenticated
